import type { Agent } from '@/types';

const HERO_LANES = [
  'walnuts_in_shell.IN.cif_cad_at_sight',
  'fresh_cherries.CN.cif_lc_at_sight',
  'table_grapes_red.CN.cif_lc_60',
];

export const agents: Agent[] = [
  // category: collect (4)
  {
    id: 'booking_confirmation_collector',
    label: 'agents.booking_confirmation_collector.label',
    description: 'agents.booking_confirmation_collector.desc',
    category: 'collect',
    tags: [],
    activeOnLanes: HERO_LANES,
  },
  {
    id: 'doc_deadline_guardian',
    label: 'agents.doc_deadline_guardian.label',
    description: 'agents.doc_deadline_guardian.desc',
    category: 'collect',
    tags: [],
    activeOnLanes: HERO_LANES,
  },
  {
    id: 'invoice_fetcher',
    label: 'agents.invoice_fetcher.label',
    description: 'agents.invoice_fetcher.desc',
    category: 'collect',
    tags: [],
    activeOnLanes: HERO_LANES,
  },
  {
    id: 'bl_tracker',
    label: 'agents.bl_tracker.label',
    description: 'agents.bl_tracker.desc',
    category: 'collect',
    tags: [],
    activeOnLanes: HERO_LANES,
  },
  // category: validate (4)
  {
    id: 'invoice_validator',
    label: 'agents.invoice_validator.label',
    description: 'agents.invoice_validator.desc',
    category: 'validate',
    tags: [],
    activeOnLanes: HERO_LANES,
  },
  {
    id: 'phyto_validator',
    label: 'agents.phyto_validator.label',
    description: 'agents.phyto_validator.desc',
    category: 'validate',
    tags: [],
    activeOnLanes: HERO_LANES,
  },
  {
    id: 'weight_reconciler',
    label: 'agents.weight_reconciler.label',
    description: 'agents.weight_reconciler.desc',
    category: 'validate',
    tags: [],
    activeOnLanes: HERO_LANES,
  },
  {
    id: 'customs_check',
    label: 'agents.customs_check.label',
    description: 'agents.customs_check.desc',
    category: 'validate',
    tags: [],
    activeOnLanes: HERO_LANES,
  },
  // category: monitor (4)
  {
    id: 'vessel_tracker',
    label: 'agents.vessel_tracker.label',
    description: 'agents.vessel_tracker.desc',
    category: 'monitor',
    tags: [],
    activeOnLanes: HERO_LANES,
  },
  {
    id: 'port_congestion_watcher',
    label: 'agents.port_congestion_watcher.label',
    description: 'agents.port_congestion_watcher.desc',
    category: 'monitor',
    tags: [],
    activeOnLanes: HERO_LANES,
  },
  {
    id: 'cutoff_sentinel',
    label: 'agents.cutoff_sentinel.label',
    description: 'agents.cutoff_sentinel.desc',
    category: 'monitor',
    tags: [],
    activeOnLanes: HERO_LANES,
  },
  {
    id: 'eta_monitor',
    label: 'agents.eta_monitor.label',
    description: 'agents.eta_monitor.desc',
    category: 'monitor',
    tags: [],
    activeOnLanes: HERO_LANES,
  },
  // category: orchestrate (3)
  {
    id: 'export_workflow_orchestrator',
    label: 'agents.export_workflow_orchestrator.label',
    description: 'agents.export_workflow_orchestrator.desc',
    category: 'orchestrate',
    tags: [],
    activeOnLanes: HERO_LANES,
  },
  {
    id: 'approval_router',
    label: 'agents.approval_router.label',
    description: 'agents.approval_router.desc',
    category: 'orchestrate',
    tags: [],
    activeOnLanes: HERO_LANES,
  },
  {
    id: 'document_assembler',
    label: 'agents.document_assembler.label',
    description: 'agents.document_assembler.desc',
    category: 'orchestrate',
    tags: [],
    activeOnLanes: HERO_LANES,
  },
  // category: reconcile (2)
  {
    id: 'po_invoice_reconciler',
    label: 'agents.po_invoice_reconciler.label',
    description: 'agents.po_invoice_reconciler.desc',
    category: 'reconcile',
    tags: [],
    activeOnLanes: HERO_LANES,
  },
  {
    id: 'freight_cost_reconciler',
    label: 'agents.freight_cost_reconciler.label',
    description: 'agents.freight_cost_reconciler.desc',
    category: 'reconcile',
    tags: [],
    activeOnLanes: HERO_LANES,
  },
  // Patch 01 additions (8)
  // Cold chain sentinels (6)
  {
    id: 'pre_cooling_tracker',
    label: 'agents.pre_cooling_tracker.label',
    description: 'agents.pre_cooling_tracker.desc',
    category: 'monitor',
    tags: ['cold_chain'],
    activeOnLanes: ['fresh_cherries.CN.cif_lc_at_sight', 'table_grapes_red.CN.cif_lc_60'],
  },
  {
    id: 'cold_storage_monitor',
    label: 'agents.cold_storage_monitor.label',
    description: 'agents.cold_storage_monitor.desc',
    category: 'monitor',
    tags: ['cold_chain'],
    activeOnLanes: ['fresh_cherries.CN.cif_lc_at_sight', 'table_grapes_red.CN.cif_lc_60'],
  },
  {
    id: 'reefer_pti_validator',
    label: 'agents.reefer_pti_validator.label',
    description: 'agents.reefer_pti_validator.desc',
    category: 'monitor',
    tags: ['cold_chain'],
    activeOnLanes: ['fresh_cherries.CN.cif_lc_at_sight', 'table_grapes_red.CN.cif_lc_60'],
  },
  {
    id: 'in_transit_telemetry_watcher',
    label: 'agents.in_transit_telemetry_watcher.label',
    description: 'agents.in_transit_telemetry_watcher.desc',
    category: 'monitor',
    tags: ['cold_chain'],
    activeOnLanes: ['fresh_cherries.CN.cif_lc_at_sight', 'table_grapes_red.CN.cif_lc_60'],
  },
  {
    id: 'cold_treatment_auditor',
    label: 'agents.cold_treatment_auditor.label',
    description: 'agents.cold_treatment_auditor.desc',
    category: 'monitor',
    tags: ['cold_chain'],
    activeOnLanes: ['fresh_cherries.CN.cif_lc_at_sight'],
  },
  {
    id: 'arrival_cold_chain_coordinator',
    label: 'agents.arrival_cold_chain_coordinator.label',
    description: 'agents.arrival_cold_chain_coordinator.desc',
    category: 'monitor',
    tags: ['cold_chain'],
    activeOnLanes: ['fresh_cherries.CN.cif_lc_at_sight', 'table_grapes_red.CN.cif_lc_60'],
  },
  // lc_discrepancy_catcher
  {
    id: 'lc_discrepancy_catcher',
    label: 'agents.lc_discrepancy_catcher.label',
    description: 'agents.lc_discrepancy_catcher.desc',
    category: 'validate',
    tags: [],
    activeOnLanes: ['fresh_cherries.CN.cif_lc_at_sight', 'table_grapes_red.CN.cif_lc_60', 'walnuts_in_shell.IN.cif_cad_at_sight'],
  },
  // lunar_new_year_window_watcher
  {
    id: 'lunar_new_year_window_watcher',
    label: 'agents.lunar_new_year_window_watcher.label',
    description: 'agents.lunar_new_year_window_watcher.desc',
    category: 'monitor',
    tags: ['seasonal', 'cn'],
    activeOnLanes: ['fresh_cherries.CN.cif_lc_at_sight', 'table_grapes_red.CN.cif_lc_60'],
  },
];
