import type { Alert } from '@/types';

export const alerts: Alert[] = [
  {
    id: 'ALT-MSCSAI4421-CUTOFF',
    bookingId: 'BKG-MSCSAI4421',
    severity: 'action',
    agentId: 'cutoff_clock',
    agentName: 'Cut-off Clock',
    agentNameEs: 'Reloj de Cut-off',
    title: 'Cut-off in 30h, no SI received',
    titleEs: 'Cut-off en 30h, sin SI recibida',
    message: 'Booking MSCSAI4421 (Comfrut → Charleston) has cut-off Fri 16:00. Comfrut typically sends SI 36h before cut-off; nothing received yet.',
    messageEs: 'Booking MSCSAI4421 (Comfrut → Charleston) tiene cut-off el vie 16:00. Comfrut normalmente envía la SI 36h antes del cut-off; aún no se ha recibido nada.',
    costAtRiskUsd: 1_800,
    createdAt: '2026-04-30T08:00:00-04:00',
    dueAt: '2026-05-01T16:00:00-04:00',
    suggestedAction: 'Email Cristián Cifuentes at logistica@comfrut.com',
    suggestedActionEs: 'Escribir a Cristián Cifuentes a logistica@comfrut.com',
  },
  {
    id: 'ALT-MAEU991033-CUTOFF',
    bookingId: 'BKG-MAEU991033',
    severity: 'action',
    agentId: 'cutoff_clock',
    agentName: 'Cut-off Clock',
    agentNameEs: 'Reloj de Cut-off',
    title: 'Cut-off in 22h, no SI received',
    titleEs: 'Cut-off en 22h, sin SI recibida',
    message: 'Booking MAEU991033 (Hortifrut → Long Beach) has cut-off Fri 08:00. SI not yet received.',
    messageEs: 'Booking MAEU991033 (Hortifrut → Long Beach) tiene cut-off el vie 08:00. SI aún no recibida.',
    costAtRiskUsd: 1_200,
    createdAt: '2026-04-30T09:30:00-04:00',
    dueAt: '2026-05-01T08:00:00-04:00',
    suggestedAction: 'Email Felipe Donoso at logistics@hortifrut.com',
    suggestedActionEs: 'Escribir a Felipe Donoso a logistics@hortifrut.com',
  },
  {
    id: 'ALT-CGMUYAN772-CUTOFF',
    bookingId: 'BKG-CGMUYAN772',
    severity: 'critical',
    agentId: 'cutoff_clock',
    agentName: 'Cut-off Clock',
    agentNameEs: 'Reloj de Cut-off',
    title: 'Cut-off in 50h, no SI for reefer to China',
    titleEs: 'Cut-off en 50h, sin SI para reefer a China',
    message: 'Booking CGMUYAN772 (Frusan fresh cherries → Yangshan, 0°C). Reefer reservation will roll if SI not in by tomorrow EOD.',
    messageEs: 'Booking CGMUYAN772 (Frusan cerezas frescas → Yangshan, 0°C). La reserva reefer se caerá si la SI no llega antes del cierre de mañana.',
    costAtRiskUsd: 2_400,
    createdAt: '2026-04-30T08:00:00-04:00',
    dueAt: '2026-05-02T12:00:00-04:00',
    suggestedAction: 'Call María José Soto at +56 2 2750 9000',
    suggestedActionEs: 'Llamar a María José Soto al +56 2 2750 9000',
  },
  {
    id: 'ALT-MSCSAI4419-CONSIGNEE',
    bookingId: 'BKG-MSCSAI4419',
    severity: 'action',
    agentId: 'master_data_sentinel',
    agentName: 'Master Data Sentinel',
    agentNameEs: 'Centinela de Datos Maestros',
    title: 'SI consignee transcription drift',
    titleEs: 'Deriva en transcripción del consignatario',
    message: 'Comfrut SI 1009571 lists consignee as "Wallmart Inc." (double-l). Master record is "Walmart Inc." Will trigger BL switch if transmitted.',
    messageEs: 'SI 1009571 de Comfrut indica consignatario "Wallmart Inc." (doble l). El registro maestro es "Walmart Inc." Provocará un switch de BL si se transmite.',
    costAtRiskUsd: 500,
    createdAt: '2026-04-29T14:25:00-04:00',
    suggestedAction: 'Reject SI back to exporter for correction',
    suggestedActionEs: 'Rechazar la SI al exportador para corrección',
  },
  {
    id: 'ALT-MAEU991028-WEIGHT',
    bookingId: 'BKG-MAEU991028',
    severity: 'action',
    agentId: 'si_validator',
    agentName: 'SI Validator',
    agentNameEs: 'Validador de SI',
    title: 'SI cargo totals do not reconcile',
    titleEs: 'Totales de carga en SI no cuadran',
    message: 'Copefrut SI declares total net 20,440 kg but cargo lines sum to 19,440 kg. Bank will reject under CAD.',
    messageEs: 'SI de Copefrut declara total neto 20.440 kg pero las líneas de carga suman 19.440 kg. El banco rechazará bajo CAD.',
    costAtRiskUsd: 350,
    createdAt: '2026-04-28T16:08:00-04:00',
    suggestedAction: 'Reject SI back to exporter for correction',
    suggestedActionEs: 'Rechazar la SI al exportador para corrección',
  },
  {
    id: 'ALT-HLCUNSA218-VESSEL',
    bookingId: 'BKG-HLCUNSA218',
    severity: 'action',
    agentId: 'si_validator',
    agentName: 'SI Validator',
    agentNameEs: 'Validador de SI',
    title: 'SI vessel name does not match Booking',
    titleEs: 'Nombre del vapor en SI no coincide con el Booking',
    message: 'Agrosuper SI declares vessel "Northern Vision" but Booking has "Northern Defender" (voyage matches). Carrier will reject SI.',
    messageEs: 'SI de Agrosuper declara vapor "Northern Vision" pero el Booking tiene "Northern Defender" (el viaje sí coincide). La naviera rechazará la SI.',
    costAtRiskUsd: 700,
    createdAt: '2026-04-29T09:32:00-04:00',
    suggestedAction: 'Reject SI back to exporter for correction',
    suggestedActionEs: 'Rechazar la SI al exportador para corrección',
  },
  {
    id: 'ALT-MSCSAI4408-BL-WEIGHT',
    bookingId: 'BKG-MSCSAI4408',
    severity: 'action',
    agentId: 'draft_bl_validator',
    agentName: 'Draft BL Validator',
    agentNameEs: 'Validador de Draft BL',
    title: 'Draft BL weight differs from SI by 0.66%',
    titleEs: 'Peso del Draft BL difiere del SI en 0,66%',
    message: 'BL declares net 23,010 kg vs SI 22,860 kg. Above 0.5% tolerance. Likely BL correction fee USD 100–500 if issued.',
    messageEs: 'BL declara neto 23.010 kg vs SI 22.860 kg. Supera tolerancia del 0,5%. Probable cargo por corrección de BL USD 100–500 si se emite.',
    costAtRiskUsd: 320,
    createdAt: '2026-04-30T07:18:00-04:00',
    suggestedAction: 'Request correction from MSC before issuance',
    suggestedActionEs: 'Solicitar corrección a MSC antes de la emisión',
  },
  {
    id: 'ALT-CGMURTM910-BL-CONSIGNEE',
    bookingId: 'BKG-CGMURTM910',
    severity: 'action',
    agentId: 'draft_bl_validator',
    agentName: 'Draft BL Validator',
    agentNameEs: 'Validador de Draft BL',
    title: 'Draft BL consignee name typo',
    titleEs: 'Error tipográfico en consignatario del Draft BL',
    message: 'BL consignee "AH Vroegop BV" missing period vs SI "AH Vroegop B.V." Bank reviewer will flag mismatch with collection order.',
    messageEs: 'Consignatario en BL "AH Vroegop BV" sin punto, vs SI "AH Vroegop B.V." El revisor bancario marcará discrepancia con la orden de cobro.',
    costAtRiskUsd: 480,
    createdAt: '2026-04-30T08:48:00-04:00',
    suggestedAction: 'Request correction from CMA-CGM before issuance',
    suggestedActionEs: 'Solicitar corrección a CMA-CGM antes de la emisión',
  },
];

export function getAlertsByBookingId(bookingId: string): Alert[] {
  return alerts.filter((a) => a.bookingId === bookingId && !a.dismissedAt);
}

export const activeAlerts = alerts.filter((a) => !a.dismissedAt);
