import type { CommercialProfile } from '@/types';

// Doc count notes (for lane composition math):
// cif_cad_at_sight: insurance_certificate (already in IN market → 0 net new for walnuts→IN lane)
// cif_lc_at_sight:  lc_compliance_letter (new!), insurance_certificate (already in CN market)
//                   → 1 net new for cherries→CN lane → 13+4+1 = 18 ✓

export const commercialProfiles: CommercialProfile[] = [
  {
    id: 'cif_cad_at_sight',
    label: 'commercial.cif_cad_at_sight',
    incoterm: 'CIF',
    paymentMethod: 'CAD',
    paymentTerms: 'Documents against payment at sight',
    requiredDocs: ['insurance_certificate'],
    validationChecks: ['INV.AMOUNT.MATCHES.PO', 'CAD.TERMS.VALID'],
    activeAgents: ['invoice_validator', 'bl_tracker'],
    bank: 'HDFC Bank',
    avgCollectionDays: 14,
    currency: 'USD',
    isDraft: false,
  },
  {
    id: 'cif_lc_at_sight',
    label: 'commercial.cif_lc_at_sight',
    incoterm: 'CIF',
    paymentMethod: 'L/C',
    paymentTerms: 'Letter of credit at sight',
    requiredDocs: ['lc_compliance_letter', 'insurance_certificate'],
    validationChecks: ['LC.TERMS.MATCH.PO', 'INV.AMOUNT.MATCHES.PO', 'BL.LC.CONSIGNEE.MATCH'],
    activeAgents: ['lc_discrepancy_catcher', 'invoice_validator', 'bl_tracker'],
    bank: 'HSBC',
    avgCollectionDays: 7,
    currency: 'USD',
    isDraft: false,
  },
  {
    id: 'cif_lc_60',
    label: 'commercial.cif_lc_60',
    incoterm: 'CIF',
    paymentMethod: 'L/C',
    paymentTerms: 'Letter of credit 60 days',
    requiredDocs: ['lc_compliance_letter', 'insurance_certificate'],
    validationChecks: ['LC.TERMS.MATCH.PO', 'INV.AMOUNT.MATCHES.PO', 'BL.LC.CONSIGNEE.MATCH'],
    activeAgents: ['lc_discrepancy_catcher', 'invoice_validator', 'bl_tracker'],
    bank: 'Bank of China',
    avgCollectionDays: 62,
    currency: 'USD',
    isDraft: false,
  },
  {
    id: 'cif_open_account_30',
    label: 'commercial.cif_open_account_30',
    incoterm: 'CIF',
    paymentMethod: 'open_account',
    paymentTerms: 'Open account 30 days',
    requiredDocs: ['insurance_certificate'],
    validationChecks: ['INV.AMOUNT.MATCHES.PO'],
    activeAgents: ['invoice_validator', 'bl_tracker'],
    bank: 'Emirates NBD',
    avgCollectionDays: 33,
    currency: 'USD',
    isDraft: false,
  },
  {
    id: 'fob_open_account_30',
    label: 'commercial.fob_open_account_30',
    incoterm: 'FOB',
    paymentMethod: 'open_account',
    paymentTerms: 'Open account 30 days',
    requiredDocs: [],
    validationChecks: ['INV.AMOUNT.MATCHES.PO'],
    activeAgents: ['invoice_validator', 'bl_tracker'],
    bank: 'Santander',
    avgCollectionDays: 38,
    currency: 'USD',
    isDraft: false,
  },
  {
    id: 'dap_open_account',
    label: 'commercial.dap_open_account',
    incoterm: 'DAP',
    paymentMethod: 'open_account',
    paymentTerms: 'Open account at delivery',
    requiredDocs: [],
    validationChecks: ['INV.AMOUNT.MATCHES.PO'],
    activeAgents: ['invoice_validator', 'bl_tracker'],
    bank: 'ABN AMRO',
    avgCollectionDays: 52,
    currency: 'USD',
    isDraft: true,
  },
];
