import type { Container, ClosedContainer } from '@/types';
import { cherriesTrace, grapesTrace } from './cold-chain-traces';

export const containers: Container[] = [
  // planning — ETD in window (T+7, 2027-01-16)
  {
    id: 'HLXU-4427109',
    productId: 'almonds_in_shell',
    productLabel: 'Almonds in shell',
    commercialId: 'cif_open_account_30',
    laneProfileId: 'almonds_in_shell.MENA.cif_open_account_30',
    market: 'MENA',
    polCode: 'CLSAI',
    polLabel: 'San Antonio',
    podCode: 'AEJEA',
    podLabel: 'Jebel Ali',
    importerId: 'IMP-MENA-ALMADINA',
    producerId: 'PRD-VF-MAULE',
    purchaseOrderId: 'PO-2026-0935',
    weightKg: 23_000,
    valueUsd: 121_000,
    carrier: 'HAPAG-LLOYD',
    polCoords: [-71.61, -33.59],
    podCoords: [55.13, 25.02],
    etd: '2027-01-16T00:00:00-04:00',
    eta: '2027-02-04T08:00:00+04:00',
    status: 'planning',
    costAtRiskUsd: 0,
    timelineNodes: [
      { tDay: -15, status: 'done' },
      { tDay: -10, status: 'done' },
      { tDay: -7, status: 'warn' },
      { tDay: 0, status: 'future' },
      { tDay: 18, status: 'future' },
    ],
  },
  // preparation — ETD in window (T+5, 2027-01-14)
  {
    id: 'MAEU-9182734',
    productId: 'fresh_cherries',
    productLabel: 'Fresh cherries',
    commercialId: 'cif_lc_at_sight',
    laneProfileId: 'fresh_cherries.CN.cif_lc_at_sight',
    market: 'CN',
    polCode: 'CLSAI',
    polLabel: 'San Antonio',
    podCode: 'CNYAN',
    podLabel: 'Yangshan',
    importerId: 'IMP-CN-DRAGON',
    producerId: 'PRD-VF-CURICO',
    purchaseOrderId: 'PO-2026-0157',
    weightKg: 22_800,
    valueUsd: 215_000,
    carrier: 'MAERSK',
    polCoords: [-71.61, -33.59],
    podCoords: [122.05, 30.63],
    etd: '2027-01-14T22:00:00-04:00',
    eta: '2027-02-08T08:00:00+08:00',
    status: 'preparation',
    coldChain: cherriesTrace,
    costAtRiskUsd: 0,
    timelineNodes: [
      { tDay: -15, status: 'done' },
      { tDay: -10, status: 'done' },
      { tDay: -5, status: 'done' },
      { tDay: 0, status: 'future' },
      { tDay: 18, status: 'future' },
    ],
  },
  // documentation — ETD in window (T+2, 2027-01-11)
  {
    id: 'MSCU-7842156',
    productId: 'walnuts_in_shell',
    productLabel: 'Walnuts in shell',
    commercialId: 'cif_cad_at_sight',
    laneProfileId: 'walnuts_in_shell.IN.cif_cad_at_sight',
    market: 'IN',
    polCode: 'CLSAI',
    polLabel: 'San Antonio',
    podCode: 'INNSA',
    podLabel: 'Nhava Sheva',
    importerId: 'IMP-IN-MUMBAI',
    producerId: 'PRD-VF-MAULE',
    purchaseOrderId: 'PO-2026-0142',
    weightKg: 24_500,
    valueUsd: 142_500,
    carrier: 'MSC',
    polCoords: [-71.61, -33.59],
    podCoords: [72.95, 18.95],
    etd: '2027-01-11T18:00:00-04:00',
    eta: '2027-02-08T08:00:00+05:30',
    cutoffAt: '2027-01-10T04:00:00-04:00',
    status: 'documentation',
    costAtRiskUsd: 8_500,
    timelineNodes: [
      { tDay: -15, status: 'done' },
      { tDay: -10, status: 'done' },
      { tDay: -7, status: 'done' },
      { tDay: -5, status: 'done' },
      { tDay: -2, status: 'crit' },
      { tDay: 0, status: 'future' },
    ],
  },
  // in_transit #1 — ETD in window (T+1, 2027-01-10)
  {
    id: 'CMAU-9281744',
    productId: 'table_grapes_red',
    productLabel: 'Table grapes (red)',
    commercialId: 'cif_lc_60',
    laneProfileId: 'table_grapes_red.CN.cif_lc_60',
    market: 'CN',
    polCode: 'CLSAI',
    polLabel: 'San Antonio',
    podCode: 'CNYAN',
    podLabel: 'Yangshan',
    importerId: 'IMP-CN-EAST',
    producerId: 'PRD-VF-OHIGGINS',
    purchaseOrderId: 'PO-2026-0163',
    weightKg: 23_400,
    valueUsd: 168_000,
    carrier: 'CMA CGM',
    polCoords: [-71.61, -33.59],
    podCoords: [114.06, 22.55],
    etd: '2027-01-10T20:00:00-04:00',
    eta: '2027-02-02T08:00:00+08:00',
    status: 'in_transit',
    coldChain: grapesTrace,
    costAtRiskUsd: 0,
    timelineNodes: [
      { tDay: -15, status: 'done' },
      { tDay: -10, status: 'done' },
      { tDay: -5, status: 'done' },
      { tDay: 0, status: 'done' },
      { tDay: 24, status: 'future' },
    ],
  },
  // in_transit #2 — ETD in window (T+4, 2027-01-13)
  {
    id: 'MSKU-3401827',
    productId: 'fresh_cherries',
    productLabel: 'Fresh cherries',
    commercialId: 'cif_lc_at_sight',
    laneProfileId: 'fresh_cherries.EU.cif_lc_at_sight',
    market: 'EU',
    polCode: 'CLVAP',
    polLabel: 'Valparaíso',
    podCode: 'ESVLC',
    podLabel: 'Valencia',
    importerId: 'IMP-EU-FRUTIMAR',
    producerId: 'PRD-VF-CURICO',
    purchaseOrderId: 'PO-2026-0941',
    weightKg: 20_000,
    valueUsd: 142_800,
    carrier: 'MAERSK',
    polCoords: [-71.62, -33.05],
    podCoords: [-0.38, 39.46],
    etd: '2027-01-13T18:00:00-04:00',
    eta: '2027-02-06T08:00:00+01:00',
    status: 'in_transit',
    costAtRiskUsd: 8_000,
    timelineNodes: [
      { tDay: -15, status: 'done' },
      { tDay: -12, status: 'warn' },
      { tDay: -10, status: 'done' },
      { tDay: -8, status: 'done' },
      { tDay: 0, status: 'done' },
      { tDay: 24, status: 'future' },
    ],
  },
  // customs_release — ETD in past
  {
    id: 'OOLU-7710443',
    productId: 'table_grapes_red',
    productLabel: 'Table grapes (red)',
    commercialId: 'cif_open_account_30',
    laneProfileId: 'table_grapes_red.CN.cif_open_account_30',
    market: 'CN',
    polCode: 'CLSAI',
    polLabel: 'San Antonio',
    podCode: 'CNSHA',
    podLabel: 'Shanghai',
    importerId: 'IMP-CN-SUNYANG',
    producerId: 'PRD-VF-OHIGGINS',
    purchaseOrderId: 'PO-2026-0928',
    weightKg: 22_000,
    valueUsd: 94_600,
    carrier: 'OOCL',
    polCoords: [-71.61, -33.59],
    podCoords: [121.47, 31.23],
    etd: '2026-12-02T00:00:00-04:00',
    eta: '2027-01-01T00:00:00+08:00',
    status: 'customs_release',
    costAtRiskUsd: 1_080,
    timelineNodes: [
      { tDay: 0, status: 'done' },
      { tDay: 18, status: 'done' },
      { tDay: 25, status: 'crit' },
      { tDay: 32, status: 'crit' },
      { tDay: 38, status: 'crit' },
    ],
  },
  // delivery_payment — ETD in past
  {
    id: 'MSCU-6128390',
    productId: 'table_grapes_white',
    productLabel: 'Table grapes (white)',
    commercialId: 'cif_cad_at_sight',
    laneProfileId: 'table_grapes_white.US.cif_cad_at_sight',
    market: 'US',
    polCode: 'CLSAI',
    polLabel: 'San Antonio',
    podCode: 'USLAX',
    podLabel: 'Los Angeles',
    importerId: 'IMP-US-PACIFIC',
    producerId: 'PRD-VF-OHIGGINS',
    purchaseOrderId: 'PO-2026-0938',
    weightKg: 24_000,
    valueUsd: 184_500,
    carrier: 'COSCO',
    polCoords: [-71.61, -33.59],
    podCoords: [-118.27, 33.74],
    etd: '2026-12-18T00:00:00-04:00',
    eta: '2027-01-07T08:00:00-08:00',
    status: 'delivery_payment',
    costAtRiskUsd: 0,
    timelineNodes: [
      { tDay: -15, status: 'done' },
      { tDay: -5, status: 'done' },
      { tDay: 0, status: 'done' },
      { tDay: 18, status: 'done' },
      { tDay: 22, status: 'crit' },
      { tDay: 25, status: 'future' },
    ],
  },
  // documentation #2 — ETD in window (T+6, 2027-01-15)
  {
    id: 'MSCU-2873561',
    productId: 'fresh_blueberries',
    productLabel: 'Fresh blueberries',
    commercialId: 'cif_lc_at_sight',
    laneProfileId: 'fresh_blueberries.EU.cif_lc_at_sight',
    market: 'EU',
    polCode: 'CLVAP',
    polLabel: 'Valparaíso',
    podCode: 'NLRTM',
    podLabel: 'Rotterdam',
    importerId: 'IMP-EU-HERITAGE',
    producerId: 'PRD-VF-BIOBIO',
    purchaseOrderId: 'PO-2026-0931',
    weightKg: 18_500,
    valueUsd: 156_200,
    carrier: 'MSC',
    polCoords: [-71.62, -33.05],
    podCoords: [4.48, 51.92],
    etd: '2027-01-15T18:00:00-04:00',
    eta: '2027-02-10T08:00:00+01:00',
    status: 'documentation',
    costAtRiskUsd: 0,
    timelineNodes: [
      { tDay: -15, status: 'done' },
      { tDay: -10, status: 'done' },
      { tDay: -6, status: 'done' },
      { tDay: 0, status: 'future' },
      { tDay: 18, status: 'future' },
    ],
  },
];

export const closedContainers: ClosedContainer[] = [
  { id: 'MSCU-1102934', buyerName: 'Pacific Produce Inc.',        cycledays: 54, deltaAvgDays: -4, penaltyUsd: 0 },
  { id: 'CMAU-7741209', buyerName: 'Heritage European Fruits BV', cycledays: 61, deltaAvgDays:  3, penaltyUsd: 0 },
  { id: 'MAEU-3398172', buyerName: 'Costco FreshCo',              cycledays: 58, deltaAvgDays:  0, penaltyUsd: 0 },
  { id: 'HLXU-2298110', buyerName: 'Mumbai Dry Fruits Pvt. Ltd.', cycledays: 55, deltaAvgDays: -3, penaltyUsd: 0 },
  { id: 'MSCU-9920183', buyerName: 'Frutimar SL',                 cycledays: 67, deltaAvgDays:  9, penaltyUsd: 1_320 },
  { id: 'OOLU-4419220', buyerName: 'Shenzhen Imports Ltd.',       cycledays: 59, deltaAvgDays:  1, penaltyUsd: 0 },
];
