import type { Exporter } from '@/types';

export const exporters: Exporter[] = [
  {
    id: 'EXP-COMFRUT',
    name: 'Comfrut',
    legalName: 'Comfrut S.A.',
    taxId: '96.928.640-0',
    address: 'Camino Longitudinal Sur Km 175, Linares',
    city: 'Linares',
    country: 'Chile',
    contactName: 'Cristián Cifuentes',
    contactEmail: 'logistica@comfrut.com',
    contactPhone: '+56 73 2 540000',
    defaultIncoterm: 'FOB',
    defaultPaymentTerm: 'COBRANZA',
    primaryProducts: ['Frozen cherries', 'Frozen berries', 'Walnuts'],
    primaryMarkets: ['US', 'EU'],
    totalOrders: 64,
    totalContainers: 412,
    onTimeSiRate: 94.2,
    siQualityScore: 91,
    avgSiTurnaroundHours: 18.5,
    logoUrl: '/logos/exporters/comfrut.png',
  },
  {
    id: 'EXP-AGROSUPER',
    name: 'Agrosuper',
    legalName: 'Agrosuper S.A.',
    taxId: '76.129.263-3',
    address: 'Av. Apoquindo 4501, Las Condes, Santiago',
    city: 'Santiago',
    country: 'Chile',
    contactName: 'Ricardo Pérez',
    contactEmail: 'export@agrosuper.com',
    contactPhone: '+56 2 2918 5000',
    defaultIncoterm: 'CIF',
    defaultPaymentTerm: 'L/C',
    primaryProducts: ['Frozen pork', 'Frozen poultry', 'Frozen salmon'],
    primaryMarkets: ['CN', 'US', 'LATAM'],
    totalOrders: 89,
    totalContainers: 731,
    onTimeSiRate: 88.6,
    siQualityScore: 86,
    avgSiTurnaroundHours: 26.2,
    logoUrl: '/logos/exporters/agrosuper.png',
  },
  {
    id: 'EXP-FRUSAN',
    name: 'Frusan',
    legalName: 'Frusan S.A.',
    taxId: '78.435.910-K',
    address: 'Av. Las Condes 11283, Santiago',
    city: 'Santiago',
    country: 'Chile',
    contactName: 'María José Soto',
    contactEmail: 'mjsoto@frusan.cl',
    contactPhone: '+56 2 2750 9000',
    defaultIncoterm: 'CFR',
    defaultPaymentTerm: 'OPEN_ACCOUNT',
    primaryProducts: ['Fresh cherries', 'Table grapes', 'Stone fruit'],
    primaryMarkets: ['CN', 'US'],
    totalOrders: 41,
    totalContainers: 287,
    onTimeSiRate: 90.8,
    siQualityScore: 88,
    avgSiTurnaroundHours: 22.0,
    logoUrl: '/logos/exporters/frusan.png',
  },
  {
    id: 'EXP-COPEFRUT',
    name: 'Copefrut',
    legalName: 'Copefrut S.A.',
    taxId: '83.043.600-0',
    address: 'Camino Las Mariposas s/n, Curicó',
    city: 'Curicó',
    country: 'Chile',
    contactName: 'Andrés Lavín',
    contactEmail: 'export@copefrut.cl',
    contactPhone: '+56 75 2 322500',
    defaultIncoterm: 'CIF',
    defaultPaymentTerm: 'CAD',
    primaryProducts: ['Apples', 'Kiwis', 'Cherries', 'Pears'],
    primaryMarkets: ['EU', 'US'],
    totalOrders: 52,
    totalContainers: 364,
    onTimeSiRate: 92.4,
    siQualityScore: 90,
    avgSiTurnaroundHours: 19.8,
    logoUrl: '/logos/exporters/copefrut.png',
  },
  {
    id: 'EXP-HORTIFRUT',
    name: 'Hortifrut',
    legalName: 'Hortifrut S.A.',
    taxId: '76.063.822-6',
    address: 'Cerro El Plomo 5630, Las Condes, Santiago',
    city: 'Santiago',
    country: 'Chile',
    contactName: 'Felipe Donoso',
    contactEmail: 'logistics@hortifrut.com',
    contactPhone: '+56 2 2840 7000',
    defaultIncoterm: 'CIF',
    defaultPaymentTerm: 'OPEN_ACCOUNT',
    primaryProducts: ['Blueberries', 'Raspberries', 'Strawberries'],
    primaryMarkets: ['US', 'EU', 'CN'],
    totalOrders: 73,
    totalContainers: 528,
    onTimeSiRate: 91.6,
    siQualityScore: 87,
    avgSiTurnaroundHours: 21.4,
    logoUrl: '/logos/exporters/hortifrut.svg',
  },
  {
    id: 'EXP-CAMPOSOL',
    name: 'Camposol Chile',
    legalName: 'Camposol Chile S.A.',
    taxId: '99.554.000-1',
    address: 'Av. del Parque 5300, Huechuraba, Santiago',
    city: 'Santiago',
    country: 'Chile',
    contactName: 'Patricia Vera',
    contactEmail: 'pvera@camposol.cl',
    contactPhone: '+56 2 2570 0500',
    defaultIncoterm: 'FOB',
    defaultPaymentTerm: 'OPEN_ACCOUNT',
    primaryProducts: ['Blueberries', 'Avocados', 'Asparagus'],
    primaryMarkets: ['US', 'EU'],
    totalOrders: 36,
    totalContainers: 218,
    onTimeSiRate: 87.3,
    siQualityScore: 83,
    avgSiTurnaroundHours: 27.6,
    logoUrl: '/logos/exporters/camposol.svg',
  },
];

export function getExporterById(id: string): Exporter | undefined {
  return exporters.find((e) => e.id === id);
}
