import type { Importer } from '@/types';

export const importers: Importer[] = [
  {
    id: 'IMP-IN-MUMBAI',
    name: 'Mumbai Dry Fruits Pvt. Ltd.',
    country: 'India',
    market: 'IN',
    activeContainers: 2,
    annualVolumeKg: 480_000,
    creditRating: 'A',
    avgPaymentDays: 12,
    volumeHistory: [
      { season: '2023/24', volumeKg: 380_000 },
      { season: '2024/25', volumeKg: 420_000 },
      { season: '2025/26', volumeKg: 450_000 },
      { season: '2026/27', volumeKg: 480_000 },
    ],
    paymentHistory: [
      { poId: 'PO-2026-0142', method: 'CAD at sight', bank: 'HDFC Bank', amount: 142_500, daysToCollect: 11, status: 'pending' },
    ],
    marketProfile: {
      inspectionAuthority: ['PQ India'],
      digitalSystem: '',
      requiredRegistrations: ['FSSAI registration'],
      labelLanguages: ['English', 'Hindi'],
    },
  },
  {
    id: 'IMP-CN-DRAGON',
    name: 'Dragon Pearl Fruits Co., Ltd.',
    country: 'China',
    market: 'CN',
    activeContainers: 3,
    annualVolumeKg: 720_000,
    creditRating: 'A+',
    avgPaymentDays: 7,
    volumeHistory: [
      { season: '2023/24', volumeKg: 540_000 },
      { season: '2024/25', volumeKg: 610_000 },
      { season: '2025/26', volumeKg: 665_000 },
      { season: '2026/27', volumeKg: 720_000 },
    ],
    paymentHistory: [
      { poId: 'PO-2026-0157', method: 'L/C a la vista', bank: 'HSBC Shanghai', amount: 215_000, daysToCollect: 6, status: 'pending' },
    ],
    marketProfile: {
      inspectionAuthority: ['GACC', 'CIQ'],
      digitalSystem: 'SAG-GACC',
      requiredRegistrations: ['GACC Decree 280 facility', 'orchard registration'],
      labelLanguages: ['Mandarin', 'English'],
      coldTreatmentOptions: ['15d @ -0.5°C'],
    },
  },
  {
    id: 'IMP-CN-EAST',
    name: 'Shenzhen Imports Ltd.',
    country: 'China',
    market: 'CN',
    activeContainers: 1,
    annualVolumeKg: 310_000,
    creditRating: 'B+',
    avgPaymentDays: 45,
    volumeHistory: [
      { season: '2023/24', volumeKg: 220_000 },
      { season: '2024/25', volumeKg: 260_000 },
      { season: '2025/26', volumeKg: 285_000 },
      { season: '2026/27', volumeKg: 310_000 },
    ],
    paymentHistory: [
      { poId: 'PO-2026-0163', method: 'L/C 60 días', bank: 'Bank of China Shenzhen', amount: 168_000, status: 'pending' },
    ],
    marketProfile: {
      inspectionAuthority: ['GACC', 'CIQ'],
      digitalSystem: 'SAG-GACC',
      requiredRegistrations: ['GACC Decree 280 facility', 'orchard registration'],
      labelLanguages: ['Mandarin', 'English'],
      coldTreatmentOptions: ['15d @ -0.5°C'],
    },
  },
  {
    id: 'IMP-US-PACIFIC',
    name: 'Pacific Produce Inc.',
    country: 'United States',
    market: 'US',
    activeContainers: 1,
    annualVolumeKg: 250_000,
    creditRating: 'A',
    avgPaymentDays: 14,
    volumeHistory: [
      { season: '2023/24', volumeKg: 180_000 },
      { season: '2024/25', volumeKg: 205_000 },
      { season: '2025/26', volumeKg: 230_000 },
      { season: '2026/27', volumeKg: 250_000 },
    ],
    paymentHistory: [
      { poId: 'PO-2026-0938', method: 'CAD at sight', bank: 'Bank of America', amount: 184_500, daysToCollect: 13, status: 'paid' },
    ],
    marketProfile: {
      inspectionAuthority: ['USDA APHIS'],
      digitalSystem: '',
      requiredRegistrations: ['FDA registration', 'CBP importer of record'],
      labelLanguages: ['English'],
      coldTreatmentOptions: ['24d @ -1°C'],
    },
  },
  {
    id: 'IMP-EU-BERLIN',
    name: 'Berlin Organic Imports GmbH',
    country: 'Germany',
    market: 'EU',
    activeContainers: 1,
    annualVolumeKg: 190_000,
    avgPaymentDays: 35,
    volumeHistory: [
      { season: '2023/24', volumeKg: 130_000 },
      { season: '2024/25', volumeKg: 150_000 },
      { season: '2025/26', volumeKg: 170_000 },
      { season: '2026/27', volumeKg: 190_000 },
    ],
    paymentHistory: [],
    marketProfile: {
      inspectionAuthority: ['EPPO + national NPPOs'],
      digitalSystem: 'TRACES NT',
      requiredRegistrations: ['EU operator registration'],
      labelLanguages: ['English'],
    },
  },
  {
    id: 'IMP-CN-SUNYANG',
    name: 'Sun Yang Foods Co.',
    country: 'China',
    market: 'CN',
    activeContainers: 1,
    annualVolumeKg: 280_000,
    avgPaymentDays: 32,
    volumeHistory: [
      { season: '2023/24', volumeKg: 190_000 },
      { season: '2024/25', volumeKg: 220_000 },
      { season: '2025/26', volumeKg: 255_000 },
      { season: '2026/27', volumeKg: 280_000 },
    ],
    paymentHistory: [
      { poId: 'PO-2026-0928', method: 'Open account 30 días', bank: 'Industrial Bank Shanghai', amount: 94_600, status: 'pending' },
    ],
    marketProfile: {
      inspectionAuthority: ['GACC', 'CIQ'],
      digitalSystem: 'SAG-GACC',
      requiredRegistrations: ['GACC Decree 280 facility', 'orchard registration'],
      labelLanguages: ['Mandarin', 'English'],
      coldTreatmentOptions: ['15d @ -0.5°C'],
    },
  },
  {
    id: 'IMP-EU-FRUTIMAR',
    name: 'Frutimar SL',
    country: 'Spain',
    market: 'EU',
    activeContainers: 2,
    annualVolumeKg: 220_000,
    creditRating: 'A',
    avgPaymentDays: 8,
    volumeHistory: [
      { season: '2023/24', volumeKg: 160_000 },
      { season: '2024/25', volumeKg: 185_000 },
      { season: '2025/26', volumeKg: 200_000 },
      { season: '2026/27', volumeKg: 220_000 },
    ],
    paymentHistory: [
      { poId: 'PO-2026-0941', method: 'L/C at sight', bank: 'Santander', amount: 142_800, daysToCollect: 7, status: 'pending' },
    ],
    marketProfile: {
      inspectionAuthority: ['EPPO + national NPPOs'],
      digitalSystem: 'TRACES NT',
      requiredRegistrations: ['EU operator registration'],
      labelLanguages: ['English'],
    },
  },
  {
    id: 'IMP-MENA-ALMADINA',
    name: 'Al Madina Trading LLC',
    country: 'UAE',
    market: 'MENA',
    activeContainers: 1,
    annualVolumeKg: 180_000,
    avgPaymentDays: 28,
    volumeHistory: [
      { season: '2023/24', volumeKg: 120_000 },
      { season: '2024/25', volumeKg: 145_000 },
      { season: '2025/26', volumeKg: 162_000 },
      { season: '2026/27', volumeKg: 180_000 },
    ],
    paymentHistory: [
      { poId: 'PO-2026-0935', method: 'Open account 30 días', bank: 'Emirates NBD', amount: 121_000, status: 'pending' },
    ],
    marketProfile: {
      inspectionAuthority: ['Ministry of Agriculture'],
      digitalSystem: '',
      requiredRegistrations: ['halal certification'],
      labelLanguages: ['Arabic', 'English'],
    },
  },
  {
    id: 'IMP-EU-HERITAGE',
    name: 'Heritage European Fruits BV',
    country: 'Netherlands',
    market: 'EU',
    activeContainers: 1,
    annualVolumeKg: 160_000,
    avgPaymentDays: 9,
    volumeHistory: [
      { season: '2023/24', volumeKg: 110_000 },
      { season: '2024/25', volumeKg: 130_000 },
      { season: '2025/26', volumeKg: 145_000 },
      { season: '2026/27', volumeKg: 160_000 },
    ],
    paymentHistory: [
      { poId: 'PO-2026-0931', method: 'L/C at sight', bank: 'ABN AMRO', amount: 156_200, daysToCollect: 8, status: 'pending' },
    ],
    marketProfile: {
      inspectionAuthority: ['EPPO + national NPPOs'],
      digitalSystem: 'TRACES NT',
      requiredRegistrations: ['EU operator registration'],
      labelLanguages: ['English'],
    },
  },
];
