import type { Naviera } from '@/types';

export const navieras: Naviera[] = [
  {
    id: 'NAV-MSC',
    name: 'Mediterranean Shipping Company',
    shortName: 'MSC',
    code: 'MSCU',
    apiCapability: 'DCSA',
    logoUrl: '/logos/navieras/msc.svg',
    totalBookings: 487,
    avgDraftBlTurnaroundHours: 24,
    siRejectionRate: 6.2,
    cutoffDisciplineRate: 94.1,
  },
  {
    id: 'NAV-CMACGM',
    name: 'CMA CGM Chile S.A.',
    shortName: 'CMA-CGM',
    code: 'CMDU',
    apiCapability: 'DCSA',
    logoUrl: '/logos/navieras/cma-cgm.svg',
    totalBookings: 412,
    avgDraftBlTurnaroundHours: 28,
    siRejectionRate: 7.8,
    cutoffDisciplineRate: 92.3,
  },
  {
    id: 'NAV-MAERSK',
    name: 'Maersk Chile',
    shortName: 'Maersk',
    code: 'MAEU',
    apiCapability: 'DCSA',
    logoUrl: '/logos/navieras/maersk.svg',
    totalBookings: 318,
    avgDraftBlTurnaroundHours: 22,
    siRejectionRate: 5.4,
    cutoffDisciplineRate: 95.7,
  },
  {
    id: 'NAV-HAPAG',
    name: 'Hapag-Lloyd',
    shortName: 'Hapag-Lloyd',
    code: 'HLCU',
    apiCapability: 'DCSA',
    logoUrl: '/logos/navieras/hapag-lloyd.svg',
    totalBookings: 203,
    avgDraftBlTurnaroundHours: 30,
    siRejectionRate: 8.1,
    cutoffDisciplineRate: 91.2,
  },
  {
    id: 'NAV-COSCO',
    name: 'COSCO Shipping Lines',
    shortName: 'COSCO',
    code: 'COSU',
    apiCapability: 'INTTRA',
    logoUrl: '/logos/navieras/cosco.svg',
    totalBookings: 174,
    avgDraftBlTurnaroundHours: 42,
    siRejectionRate: 11.4,
    cutoffDisciplineRate: 87.5,
  },
  {
    id: 'NAV-ONE',
    name: 'Ocean Network Express',
    shortName: 'ONE',
    code: 'ONEY',
    apiCapability: 'DCSA',
    logoUrl: '/logos/navieras/one.svg',
    totalBookings: 142,
    avgDraftBlTurnaroundHours: 26,
    siRejectionRate: 7.0,
    cutoffDisciplineRate: 93.4,
  },
  {
    id: 'NAV-EVERGREEN',
    name: 'Evergreen Marine',
    shortName: 'Evergreen',
    code: 'EGLV',
    apiCapability: 'INTTRA',
    logoUrl: '/logos/navieras/evergreen.svg',
    totalBookings: 98,
    avgDraftBlTurnaroundHours: 48,
    siRejectionRate: 12.6,
    cutoffDisciplineRate: 86.8,
  },
  {
    id: 'NAV-HMM',
    name: 'Hyundai Merchant Marine',
    shortName: 'HMM',
    code: 'HDMU',
    apiCapability: 'manual',
    logoUrl: '/logos/navieras/hmm.svg',
    totalBookings: 61,
    avgDraftBlTurnaroundHours: 68,
    siRejectionRate: 14.9,
    cutoffDisciplineRate: 82.1,
  },
];

export function getNavieraById(id: string): Naviera | undefined {
  return navieras.find((n) => n.id === id);
}

export const SCAC_TO_NAVIERA_ID: Record<string, string> = {
  CMDU: 'NAV-CMACGM',
  MSCU: 'NAV-MSC',
  MAEU: 'NAV-MAERSK',
  HLCU: 'NAV-HAPAG',
  COSU: 'NAV-COSCO',
  ONEY: 'NAV-ONE',
  EGLV: 'NAV-EVERGREEN',
};
