import type { PenaltyEvent } from '@/types';

export const penaltyEvents: PenaltyEvent[] = [
  {
    id: 'PEN-NO-SHOW',
    stage: 'pre_cutoff',
    event: 'No-show booking',
    trigger: 'Container missed cut-off',
    usdMin: 300,
    usdMax: 800,
    avoidedBy: 'cutoff_clock',
  },
  {
    id: 'PEN-VESSEL-ROLL',
    stage: 't0',
    event: 'Vessel rolled',
    trigger: 'Cargo cut-off missed',
    usdMin: 1_500,
    usdMax: 4_000,
    avoidedBy: 'cutoff_clock',
  },
  {
    id: 'PEN-BL-CORRECTION',
    stage: 't1',
    event: 'BL correction (post-issue)',
    trigger: 'Typo, weight, marks or consignee error',
    usdMin: 100,
    usdMax: 500,
    avoidedBy: 'draft_bl_validator',
  },
  {
    id: 'PEN-BL-SWITCH',
    stage: 't2',
    event: 'BL switch (post-manifest)',
    trigger: 'Change of consignee or notify',
    usdMin: 200,
    usdMax: 1_500,
    avoidedBy: 'draft_bl_validator',
  },
  {
    id: 'PEN-BANK-DISC',
    stage: 't3',
    event: 'Bank discrepancy fee',
    trigger: 'SI inconsistent with collection order',
    usdMin: 75,
    usdMax: 150,
    avoidedBy: 'si_validator',
  },
  {
    id: 'PEN-DEMURRAGE-BL',
    stage: 't5',
    event: 'Demurrage from BL error',
    trigger: 'BL incorrect, port hold',
    usdMin: 200,
    usdMax: 200,
    avoidedBy: 'draft_bl_validator',
  },
];
