import type { ProductProfile } from '@/types';

// Doc count notes (for lane composition math):
// walnuts_in_shell (10 docs):
//   commercial_invoice, packing_list, bill_of_lading, certificate_of_origin,
//   phyto_certificate, fumigation_cert, health_cert, dus, sag_export_auth, transport_document
//   → no cold-chain docs
//
// fresh_cherries (13 docs):
//   commercial_invoice, packing_list, bill_of_lading, certificate_of_origin,
//   phyto_certificate, health_cert, cold_treatment_cert, pti_certificate,
//   pre_cooling_log, logger_report, ca_atmosphere_log, dus, transport_document

export const productProfiles: ProductProfile[] = [
  {
    id: 'walnuts_in_shell',
    label: 'products.walnuts_in_shell',
    requiresColdChain: false,
    defaultProtocols: [],
    seasonality: 'Sep–Jan',
    hsCode: '0802.31',
    // 10 docs — no cold-chain; overlaps with IN market: phyto_certificate, health_cert,
    // sag_export_auth, fumigation_cert, certificate_of_origin (5 overlaps)
    requiredDocs: [
      'commercial_invoice',
      'packing_list',
      'bill_of_lading',
      'certificate_of_origin',
      'phyto_certificate',
      'fumigation_cert',
      'health_cert',
      'dus',
      'sag_export_auth',
      'transport_document',
    ],
    activeAgents: ['doc_deadline_guardian', 'invoice_validator', 'vessel_tracker'],
  },
  {
    id: 'walnut_kernels',
    label: 'products.walnut_kernels',
    requiresColdChain: false,
    defaultProtocols: [],
    seasonality: 'Sep–Jan',
    hsCode: '0802.32',
    requiredDocs: [
      'commercial_invoice',
      'packing_list',
      'bill_of_lading',
      'certificate_of_origin',
      'phyto_certificate',
      'fumigation_cert',
      'health_cert',
      'dus',
      'transport_document',
    ],
    activeAgents: ['doc_deadline_guardian', 'invoice_validator', 'vessel_tracker'],
  },
  {
    id: 'almonds_in_shell',
    label: 'products.almonds_in_shell',
    requiresColdChain: false,
    defaultProtocols: [],
    seasonality: 'Aug–Dec',
    hsCode: '0802.11',
    requiredDocs: [
      'commercial_invoice',
      'packing_list',
      'bill_of_lading',
      'certificate_of_origin',
      'phyto_certificate',
      'fumigation_cert',
      'health_cert',
      'dus',
      'transport_document',
    ],
    activeAgents: ['doc_deadline_guardian', 'invoice_validator', 'vessel_tracker'],
  },
  {
    id: 'fresh_cherries',
    label: 'products.fresh_cherries',
    requiresColdChain: true,
    defaultProtocols: ['china_15d_0_5c'],
    seasonality: 'Nov–Jan',
    hsCode: '0809.29',
    // 13 docs — full cold-chain set; overlaps with CN market: phyto_certificate, health_cert,
    // cold_treatment_cert, pti_certificate, pre_cooling_log, logger_report,
    // ca_atmosphere_log, certificate_of_origin (8 overlaps)
    requiredDocs: [
      'commercial_invoice',
      'packing_list',
      'bill_of_lading',
      'certificate_of_origin',
      'phyto_certificate',
      'health_cert',
      'cold_treatment_cert',
      'pti_certificate',
      'pre_cooling_log',
      'logger_report',
      'ca_atmosphere_log',
      'dus',
      'transport_document',
    ],
    activeAgents: [
      'pre_cooling_tracker',
      'cold_storage_monitor',
      'reefer_pti_validator',
      'in_transit_telemetry_watcher',
      'cold_treatment_auditor',
      'arrival_cold_chain_coordinator',
      'vessel_tracker',
      'doc_deadline_guardian',
    ],
  },
  {
    id: 'fresh_blueberries',
    label: 'products.fresh_blueberries',
    requiresColdChain: true,
    defaultProtocols: ['us_jh_24d_neg_1c'],
    seasonality: 'Oct–Dec',
    hsCode: '0810.40',
    requiredDocs: [
      'commercial_invoice',
      'packing_list',
      'bill_of_lading',
      'certificate_of_origin',
      'phyto_certificate',
      'health_cert',
      'cold_treatment_cert',
      'pti_certificate',
      'pre_cooling_log',
      'logger_report',
      'dus',
      'transport_document',
    ],
    activeAgents: [
      'pre_cooling_tracker',
      'cold_storage_monitor',
      'reefer_pti_validator',
      'in_transit_telemetry_watcher',
      'vessel_tracker',
      'doc_deadline_guardian',
    ],
  },
  {
    id: 'table_grapes_red',
    label: 'products.table_grapes_red',
    requiresColdChain: true,
    defaultProtocols: ['china_15d_0_5c'],
    seasonality: 'Jan–Mar',
    hsCode: '0806.10',
    requiredDocs: [
      'commercial_invoice',
      'packing_list',
      'bill_of_lading',
      'certificate_of_origin',
      'phyto_certificate',
      'health_cert',
      'cold_treatment_cert',
      'pti_certificate',
      'pre_cooling_log',
      'logger_report',
      'dus',
      'transport_document',
    ],
    activeAgents: [
      'pre_cooling_tracker',
      'cold_storage_monitor',
      'reefer_pti_validator',
      'in_transit_telemetry_watcher',
      'arrival_cold_chain_coordinator',
      'vessel_tracker',
      'doc_deadline_guardian',
    ],
  },
  {
    id: 'table_grapes_white',
    label: 'products.table_grapes_white',
    requiresColdChain: true,
    defaultProtocols: ['china_15d_0_5c'],
    seasonality: 'Jan–Mar',
    hsCode: '0806.10',
    requiredDocs: [
      'commercial_invoice',
      'packing_list',
      'bill_of_lading',
      'certificate_of_origin',
      'phyto_certificate',
      'health_cert',
      'cold_treatment_cert',
      'pti_certificate',
      'pre_cooling_log',
      'logger_report',
      'dus',
      'transport_document',
    ],
    activeAgents: [
      'pre_cooling_tracker',
      'cold_storage_monitor',
      'reefer_pti_validator',
      'in_transit_telemetry_watcher',
      'arrival_cold_chain_coordinator',
      'vessel_tracker',
      'doc_deadline_guardian',
    ],
  },
];
