import type { Producer } from '@/types';

export const producers: Producer[] = [
  {
    id: 'PRD-VF-MAULE',
    name: 'Valle Fresco — Maule',
    region: 'Maule',
    products: ['walnuts_in_shell', 'walnut_kernels'],
    sagId: 'SAG-MAU-00412',
    activeContainers: 2,
    avgPaymentDays: 30,
    volumeHistory: [
      { season: '2023/24', volumeKg: 14_200 },
      { season: '2024/25', volumeKg: 18_800 },
      { season: '2025/26', volumeKg: 21_500 },
      { season: '2026/27', volumeKg: 22_800 },
    ],
    certifiedProducts: [
      {
        productId: 'walnuts_in_shell',
        name: 'Walnuts in Shell',
        hsCode: '0802.31',
        seasonStart: 'Sep',
        seasonEnd: 'Jan',
        requiresColdChain: false,
        enabledMarkets: ['IN', 'MENA', 'EU'],
      },
      {
        productId: 'walnut_kernels',
        name: 'Walnut Kernels',
        hsCode: '0802.32',
        seasonStart: 'Sep',
        seasonEnd: 'Jan',
        requiresColdChain: false,
        enabledMarkets: ['US', 'EU'],
      },
    ],
    sagCertifications: [
      {
        id: 'SAG-MAU-00412',
        name: 'Export Authorization',
        expiryDate: '2027-08-31',
        daysUntilExpiry: 234,
      },
      {
        id: 'SAG-MAU-00412-F',
        name: 'Fumigation Facility Approval',
        // warn: expires 2027-02-14 → 36 days after demo date 2027-01-09
        expiryDate: '2027-02-14',
        daysUntilExpiry: 36,
      },
    ],
  },
  {
    id: 'PRD-VF-CURICO',
    name: 'Valle Fresco — Curicó',
    region: 'Curicó',
    products: ['fresh_cherries', 'fresh_blueberries'],
    sagId: 'SAG-CUR-00288',
    activeContainers: 1,
    avgPaymentDays: 28,
    volumeHistory: [
      { season: '2023/24', volumeKg: 18_500 },
      { season: '2024/25', volumeKg: 22_100 },
      { season: '2025/26', volumeKg: 25_800 },
      { season: '2026/27', volumeKg: 27_400 },
    ],
    certifiedProducts: [
      {
        productId: 'fresh_cherries',
        name: 'Fresh Cherries',
        hsCode: '0809.29',
        seasonStart: 'Nov',
        seasonEnd: 'Jan',
        requiresColdChain: true,
        coldProtocol: 'china_15d_0_5c',
        enabledMarkets: ['CN', 'EU', 'US'],
      },
      {
        productId: 'fresh_blueberries',
        name: 'Fresh Blueberries',
        hsCode: '0810.40',
        seasonStart: 'Oct',
        seasonEnd: 'Dec',
        requiresColdChain: true,
        coldProtocol: 'us_jh_24d_neg_1c',
        enabledMarkets: ['EU', 'US'],
      },
    ],
    sagCertifications: [
      {
        id: 'SAG-CUR-00288',
        name: 'Export Authorization',
        // crit: expires 2027-01-17 → 8 days after demo date 2027-01-09
        expiryDate: '2027-01-17',
        daysUntilExpiry: 8,
      },
      {
        id: 'SAG-CUR-00288-CC',
        name: 'Cold Treatment Facility Certification',
        expiryDate: '2027-06-30',
        daysUntilExpiry: 172,
      },
    ],
  },
  {
    id: "PRD-VF-OHIGGINS",
    name: "Valle Fresco — O'Higgins",
    region: "O'Higgins",
    products: ['table_grapes_red', 'table_grapes_white'],
    sagId: 'SAG-OHI-00331',
    activeContainers: 1,
    avgPaymentDays: 32,
    volumeHistory: [
      { season: '2023/24', volumeKg: 22_000 },
      { season: '2024/25', volumeKg: 26_500 },
      { season: '2025/26', volumeKg: 29_800 },
      { season: '2026/27', volumeKg: 31_200 },
    ],
    certifiedProducts: [
      {
        productId: 'table_grapes_red',
        name: 'Table Grapes (Red)',
        hsCode: '0806.10',
        seasonStart: 'Jan',
        seasonEnd: 'Mar',
        requiresColdChain: true,
        coldProtocol: 'china_15d_0_5c',
        enabledMarkets: ['CN', 'US', 'EU'],
      },
      {
        productId: 'table_grapes_white',
        name: 'Table Grapes (White)',
        hsCode: '0806.10',
        seasonStart: 'Jan',
        seasonEnd: 'Mar',
        requiresColdChain: true,
        coldProtocol: 'china_15d_0_5c',
        enabledMarkets: ['CN', 'US', 'EU'],
      },
    ],
    sagCertifications: [
      {
        id: 'SAG-OHI-00331',
        name: 'Export Authorization',
        expiryDate: '2027-07-31',
        daysUntilExpiry: 203,
      },
      {
        id: 'SAG-OHI-00331-P',
        name: 'Phytosanitary Pre-Inspection Approval',
        expiryDate: '2027-09-15',
        daysUntilExpiry: 249,
      },
    ],
  },
  {
    id: 'PRD-EXT-COLCHAGUA',
    name: 'Viñedos Colchagua',
    region: 'Colchagua',
    products: ['table_grapes_red'],
    sagId: 'SAG-COL-00178',
    activeContainers: 0,
    avgPaymentDays: 35,
    volumeHistory: [
      { season: '2023/24', volumeKg: 8_400 },
      { season: '2024/25', volumeKg: 9_200 },
      { season: '2025/26', volumeKg: 10_100 },
      { season: '2026/27', volumeKg: 11_000 },
    ],
    certifiedProducts: [
      {
        productId: 'table_grapes_red',
        name: 'Table Grapes (Red)',
        hsCode: '0806.10',
        seasonStart: 'Jan',
        seasonEnd: 'Mar',
        requiresColdChain: true,
        coldProtocol: 'china_15d_0_5c',
        enabledMarkets: ['CN', 'EU'],
      },
    ],
    sagCertifications: [
      {
        id: 'SAG-COL-00178',
        name: 'Export Authorization',
        expiryDate: '2027-10-31',
        daysUntilExpiry: 295,
      },
    ],
  },
  {
    id: 'PRD-VF-BIOBIO',
    name: 'Valle Fresco — Bío-Bío',
    region: 'Bío-Bío',
    products: ['fresh_blueberries'],
    sagId: 'SAG-BIO-00519',
    activeContainers: 1,
    avgPaymentDays: 30,
    volumeHistory: [
      { season: '2023/24', volumeKg: 11_000 },
      { season: '2024/25', volumeKg: 13_500 },
      { season: '2025/26', volumeKg: 15_200 },
      { season: '2026/27', volumeKg: 16_800 },
    ],
    certifiedProducts: [
      {
        productId: 'fresh_blueberries',
        name: 'Fresh Blueberries',
        hsCode: '0810.40',
        seasonStart: 'Oct',
        seasonEnd: 'Dec',
        requiresColdChain: true,
        coldProtocol: 'us_jh_24d_neg_1c',
        enabledMarkets: ['EU', 'US'],
      },
    ],
    sagCertifications: [
      {
        id: 'SAG-BIO-00519',
        name: 'Export Authorization',
        expiryDate: '2027-08-15',
        daysUntilExpiry: 218,
      },
      {
        id: 'SAG-BIO-00519-CC',
        name: 'Cold Chain Facility Certification',
        expiryDate: '2027-05-31',
        daysUntilExpiry: 142,
      },
    ],
  },
];
