import type { ShippingInstruction, ValidationCheck } from '@/types';

const heroValidationChecks: ValidationCheck[] = [
  { id: 'CHK-1', checkName: 'Booking reference match', agentId: 'si_validator', result: 'pass', details: 'SI booking reference matches Booking SNG0502407.' },
  { id: 'CHK-2', checkName: 'Container type match', agentId: 'si_validator', result: 'pass', details: '40RF on both SI and Booking.' },
  { id: 'CHK-3', checkName: 'POL match', agentId: 'si_validator', result: 'pass', details: 'San Antonio on both SI and Booking.' },
  { id: 'CHK-4', checkName: 'POD match', agentId: 'si_validator', result: 'pass', details: 'Charleston on both SI and Booking.' },
  { id: 'CHK-5', checkName: 'Cut-off match', agentId: 'si_validator', result: 'pass', details: 'Cut-off 21 Apr 14:00 matches Booking.' },
  { id: 'CHK-6', checkName: 'Vessel/voyage match', agentId: 'si_validator', result: 'pass', details: 'Matthew Schulte / 0LI1YN1MA on both.' },
  { id: 'CHK-7', checkName: 'Required fields present', agentId: 'si_validator', result: 'pass', details: 'Consignee, notify, shipper, vessel, voyage all populated.' },
  { id: 'CHK-8', checkName: 'Cargo totals reconcile', agentId: 'si_validator', result: 'pass', details: 'Net 22,860.00 kg matches sum of cargo lines (within 0.01%).' },
  { id: 'CHK-9', checkName: 'Reefer setpoint present', agentId: 'si_validator', result: 'pass', details: 'Reefer container declared at −18 °C.' },
  { id: 'CHK-10', checkName: 'Exporter master data match', agentId: 'master_data_sentinel', result: 'pass', details: 'Shipper "Comfrut S.A." matches Exporter master data exactly.' },
];

export const shippingInstructions: ShippingInstruction[] = [
  // ============================================================
  // HERO — Comfrut Embarque 1009562 → Booking SNG0502407
  // Mirrors the real Instructivo de Agente PDF.
  // ============================================================
  {
    id: 'SI-SNG0502407',
    bookingId: 'BKG-SNG0502407',
    receivedAt: '2026-04-19T11:42:00-04:00',
    sourceFileUrl: '/mock-docs/comfrut-1009562-si.pdf',
    sourceFileName: 'Instructivo_de_Agente_para_Embarque_1009562.PDF',
    uploadedVia: 'portal',
    parsedFields: {
      embarqueNumber: '1009562',
      poNumber: 'WMT-CH-2026-04421',
      portOfLoading: 'San Antonio, Chile',
      portOfDischarge: 'Charleston, USA',
      finalDestination: 'Bentonville, AR, USA',
      vesselVoyage: 'Matthew Schulte / 0LI1YN1MA',
      naviera: 'CMA CGM Chile S.A.',
      forwarder: 'Interglobo Chile',
      bookingReference: 'SNG0502407',
      blNumber: 'CGMUSAI3052801',
      salesModality: 'Venta a Firme',
      paymentForm: 'COBRANZA',
      incoterm: 'FOB',
      containerCount: '1 UNIDAD REEFER 40 H.C',
      containerType: '40RF',
      setpointC: -18,
      deposito: 'Saam Extraportuario San Antonio',
      generator: 'POR CUENTA DEL TRANSPORTE',
      transport: 'Transportes Andinos Ltda.',
      truckType: 'Tractocamión 6x4 con plataforma reefer 40\'',
      freightTerms: 'COLLECT',
      returnPeriod: '270 DIAS',
      plant: {
        name: 'Comfrut S.A. — Planta Linares',
        address: 'Camino Longitudinal Sur Km 175, Linares',
        contact: 'Cristián Cifuentes · +56 73 2 540000',
      },
      loadingDate: '2026-04-20T09:00:00-04:00',
      portArrivalDate: '2026-04-20T18:00:00-04:00',
      stackingFrom: '2026-04-19T08:00:00-04:00',
      stackingTo: '2026-04-21T12:00:00-04:00',
      cutOff: '2026-04-21T14:00:00-04:00',
      consignee: {
        name: 'Walmart Inc.',
        address: '702 SW 8th St, Bentonville, AR 72716, USA',
      },
      notify: {
        name: 'Expeditors International — Savannah',
        address: '1 Diamond Causeway, Savannah, GA 31406, USA',
      },
      alsoNotify: {
        name: 'Walmart Imports Customs',
        address: '601 N Walton Blvd, Bentonville, AR 72716, USA',
      },
      shipper: {
        name: 'Comfrut S.A.',
        address: 'Camino Longitudinal Sur Km 175, Linares, Chile',
      },
      cargo: [
        {
          product: 'KILOS CEREZAS ORGANICO CONGELADO IQF 5x2 KG',
          kgNetUnit: 10.0,
          kgGrossUnit: 10.6,
          qty: 1140,
          kgNetTotal: 11_400.0,
          kgGrossTotal: 12_084.0,
          fobPrice: 5.85,
        },
        {
          product: 'KILOS CEREZAS ORGANICO CONGELADO IQF 10 KG',
          kgNetUnit: 10.0,
          kgGrossUnit: 10.55,
          qty: 1146,
          kgNetTotal: 11_460.0,
          kgGrossTotal: 12_090.3,
          fobPrice: 5.92,
        },
      ],
      totalKgNet: 22_860.0,
      totalKgGross: 24_174.3,
    },
    validationStatus: 'green',
    validationResults: heroValidationChecks,
    esiGeneratedAt: '2026-04-19T12:08:00-04:00',
    esiTransmittedAt: '2026-04-19T12:11:00-04:00',
    esiTransmissionStatus: 'acknowledged',
  },

  // ============================================================
  // SI_FAILED examples — concrete validation failures
  // ============================================================
  {
    id: 'SI-MSCSAI4419',
    bookingId: 'BKG-MSCSAI4419',
    receivedAt: '2026-04-29T14:20:00-04:00',
    sourceFileUrl: '/mock-docs/comfrut-1009562-si.pdf',
    sourceFileName: 'SI_Comfrut_MSCSAI4419.pdf',
    uploadedVia: 'portal',
    parsedFields: {
      embarqueNumber: '1009571',
      portOfLoading: 'San Antonio, Chile',
      portOfDischarge: 'Charleston, USA',
      finalDestination: 'Bentonville, AR, USA',
      vesselVoyage: 'MSC Antonia / EX2614R',
      naviera: 'Mediterranean Shipping Company',
      forwarder: 'Interglobo Chile',
      bookingReference: 'MSCSAI4419',
      salesModality: 'Venta a Firme',
      paymentForm: 'COBRANZA',
      incoterm: 'FOB',
      containerCount: '1 UNIDAD REEFER 40 H.C',
      containerType: '40RF',
      setpointC: -18,
      deposito: 'Saam Extraportuario San Antonio',
      generator: 'POR CUENTA DEL TRANSPORTE',
      transport: 'Transportes Andinos Ltda.',
      truckType: 'Tractocamión 6x4 con plataforma reefer 40\'',
      freightTerms: 'COLLECT',
      returnPeriod: '270 DIAS',
      plant: {
        name: 'Comfrut S.A. — Planta Linares',
        address: 'Camino Longitudinal Sur Km 175, Linares',
        contact: 'Cristián Cifuentes · +56 73 2 540000',
      },
      loadingDate: '2026-04-30T09:00:00-04:00',
      portArrivalDate: '2026-04-30T18:00:00-04:00',
      stackingFrom: '2026-04-29T08:00:00-04:00',
      stackingTo: '2026-05-01T14:00:00-04:00',
      cutOff: '2026-05-01T16:00:00-04:00',
      consignee: {
        name: 'Wallmart Inc.',
        address: '702 SW 8th St, Bentonville, AR 72716, USA',
      },
      notify: {
        name: 'Expeditors International — Savannah',
        address: '1 Diamond Causeway, Savannah, GA 31406, USA',
      },
      shipper: {
        name: 'Comfrut S.A.',
        address: 'Camino Longitudinal Sur Km 175, Linares, Chile',
      },
      cargo: [
        {
          product: 'KILOS CEREZAS CONVENCIONAL CONGELADO IQF 5x2 KG',
          kgNetUnit: 10.0,
          kgGrossUnit: 10.6,
          qty: 2280,
          kgNetTotal: 22_800.0,
          kgGrossTotal: 24_168.0,
          fobPrice: 4.95,
        },
      ],
      totalKgNet: 22_800.0,
      totalKgGross: 24_168.0,
    },
    validationStatus: 'failed',
    validationResults: [
      { id: 'CHK-1', checkName: 'Booking reference match', agentId: 'si_validator', result: 'pass', details: 'Matches Booking MSCSAI4419.' },
      { id: 'CHK-2', checkName: 'Container type match', agentId: 'si_validator', result: 'pass', details: '40RF on both.' },
      { id: 'CHK-3', checkName: 'POL match', agentId: 'si_validator', result: 'pass', details: 'San Antonio on both.' },
      { id: 'CHK-4', checkName: 'POD match', agentId: 'si_validator', result: 'pass', details: 'Charleston on both.' },
      { id: 'CHK-5', checkName: 'Cut-off match', agentId: 'si_validator', result: 'pass', details: 'Cut-off matches Booking.' },
      { id: 'CHK-6', checkName: 'Vessel/voyage match', agentId: 'si_validator', result: 'pass', details: 'MSC Antonia / EX2614R on both.' },
      { id: 'CHK-7', checkName: 'Required fields present', agentId: 'si_validator', result: 'pass', details: 'All required fields present.' },
      { id: 'CHK-8', checkName: 'Cargo totals reconcile', agentId: 'si_validator', result: 'pass', details: 'Totals reconcile.' },
      { id: 'CHK-9', checkName: 'Reefer setpoint present', agentId: 'si_validator', result: 'pass', details: 'Setpoint −18 °C declared.' },
      { id: 'CHK-10', checkName: 'Exporter master data match', agentId: 'master_data_sentinel', result: 'fail', details: 'Consignee "Wallmart Inc." does not match the master record. Comfrut\'s last 12 SIs to this lane all used "Walmart Inc." (single l). Likely a typo; will trigger a BL switch fee if transmitted as-is.', fieldRef: 'consignee.name', expected: 'Walmart Inc.', actual: 'Wallmart Inc.' },
    ],
  },
  {
    id: 'SI-MAEU991028',
    bookingId: 'BKG-MAEU991028',
    receivedAt: '2026-04-28T16:05:00-04:00',
    sourceFileUrl: '/mock-docs/comfrut-1009562-si.pdf',
    sourceFileName: 'SI_Copefrut_MAEU991028.pdf',
    uploadedVia: 'email',
    parsedFields: {
      embarqueNumber: 'CPF-2026-1241',
      portOfLoading: 'San Antonio, Chile',
      portOfDischarge: 'Rotterdam, Netherlands',
      finalDestination: 'Rotterdam, Netherlands',
      vesselVoyage: 'Maersk Lavras / 614N',
      naviera: 'Maersk Chile',
      forwarder: 'Interglobo Chile',
      bookingReference: 'MAEU991028',
      salesModality: 'Venta a Firme',
      paymentForm: 'CAD',
      incoterm: 'CIF',
      containerCount: '1 UNIDAD REEFER 40 H.C',
      containerType: '40RF',
      setpointC: 0,
      deposito: 'STI San Antonio',
      generator: 'POR CUENTA DEL TRANSPORTE',
      transport: 'Sotraser',
      truckType: 'Tractocamión 6x4 reefer 40\'',
      freightTerms: 'PREPAID',
      returnPeriod: '180 DIAS',
      plant: {
        name: 'Copefrut S.A. — Planta Curicó',
        address: 'Camino Las Mariposas s/n, Curicó',
        contact: 'Andrés Lavín · +56 75 2 322500',
      },
      loadingDate: '2026-05-01T09:00:00-04:00',
      portArrivalDate: '2026-05-01T18:00:00-04:00',
      stackingFrom: '2026-04-30T08:00:00-04:00',
      stackingTo: '2026-05-02T06:00:00-04:00',
      cutOff: '2026-05-02T08:00:00-04:00',
      consignee: {
        name: 'AH Vroegop B.V.',
        address: 'Waalhaven Z.z. 16, 3088 HH Rotterdam, NL',
      },
      notify: {
        name: 'AH Vroegop B.V.',
        address: 'Waalhaven Z.z. 16, 3088 HH Rotterdam, NL',
      },
      shipper: {
        name: 'Copefrut S.A.',
        address: 'Camino Las Mariposas s/n, Curicó, Chile',
      },
      cargo: [
        {
          product: 'KILOS MANZANA GALA EXPORT 18 KG',
          kgNetUnit: 18.0,
          kgGrossUnit: 19.0,
          qty: 1080,
          kgNetTotal: 19_440.0,
          kgGrossTotal: 20_520.0,
          fobPrice: 1.42,
        },
      ],
      totalKgNet: 20_440.0,
      totalKgGross: 20_520.0,
    },
    validationStatus: 'failed',
    validationResults: [
      { id: 'CHK-1', checkName: 'Booking reference match', agentId: 'si_validator', result: 'pass', details: 'Matches Booking MAEU991028.' },
      { id: 'CHK-2', checkName: 'Container type match', agentId: 'si_validator', result: 'pass', details: '40RF on both.' },
      { id: 'CHK-3', checkName: 'POL match', agentId: 'si_validator', result: 'pass', details: 'San Antonio on both.' },
      { id: 'CHK-4', checkName: 'POD match', agentId: 'si_validator', result: 'pass', details: 'Rotterdam on both.' },
      { id: 'CHK-5', checkName: 'Cut-off match', agentId: 'si_validator', result: 'pass', details: 'Cut-off matches Booking.' },
      { id: 'CHK-6', checkName: 'Vessel/voyage match', agentId: 'si_validator', result: 'pass', details: 'Maersk Lavras / 614N on both.' },
      { id: 'CHK-7', checkName: 'Required fields present', agentId: 'si_validator', result: 'pass', details: 'All required fields present.' },
      { id: 'CHK-8', checkName: 'Cargo totals reconcile', agentId: 'si_validator', result: 'fail', details: 'Sum of cargo line net weights is 19,440.00 kg but totalKgNet is declared as 20,440.00 kg. Bank will reject under CAD if invoice mirrors the SI.', fieldRef: 'totalKgNet', expected: '19,440.00 kg', actual: '20,440.00 kg' },
      { id: 'CHK-9', checkName: 'Reefer setpoint present', agentId: 'si_validator', result: 'pass', details: 'Setpoint 0 °C declared (apples ambient-equivalent).' },
      { id: 'CHK-10', checkName: 'Exporter master data match', agentId: 'master_data_sentinel', result: 'pass', details: 'Shipper "Copefrut S.A." matches master record.' },
    ],
  },
  {
    id: 'SI-HLCUNSA218',
    bookingId: 'BKG-HLCUNSA218',
    receivedAt: '2026-04-29T09:30:00-04:00',
    sourceFileUrl: '/mock-docs/comfrut-1009562-si.pdf',
    sourceFileName: 'SI_Agrosuper_HLCUNSA218.pdf',
    uploadedVia: 'portal',
    parsedFields: {
      embarqueNumber: 'AGS-EX-2026-0418',
      portOfLoading: 'San Antonio, Chile',
      portOfDischarge: 'Nhava Sheva, India',
      finalDestination: 'Mumbai, India',
      vesselVoyage: 'Northern Vision / 0218W',
      naviera: 'Hapag-Lloyd',
      forwarder: 'Interglobo Chile',
      bookingReference: 'HLCUNSA218',
      salesModality: 'Venta a Firme',
      paymentForm: 'L/C',
      incoterm: 'CIF',
      containerCount: '1 UNIDAD DRY 40 H.C',
      containerType: '40HC',
      deposito: 'STI San Antonio',
      generator: '—',
      transport: 'Transportes Andinos Ltda.',
      truckType: 'Tractocamión 6x4 dry 40\'',
      freightTerms: 'PREPAID',
      returnPeriod: '180 DIAS',
      plant: {
        name: 'Agrosuper — Planta Rancagua',
        address: 'Av. Apoquindo 4501, Las Condes, Santiago',
        contact: 'Ricardo Pérez · +56 2 2918 5000',
      },
      loadingDate: '2026-05-01T09:00:00-04:00',
      portArrivalDate: '2026-05-01T18:00:00-04:00',
      stackingFrom: '2026-04-29T08:00:00-04:00',
      stackingTo: '2026-05-01T16:00:00-04:00',
      cutOff: '2026-05-01T18:00:00-04:00',
      consignee: {
        name: 'Allana Sons Pvt. Ltd.',
        address: 'Allana House, Currimbhoy Rd, Mumbai 400001, India',
      },
      notify: {
        name: 'Allana Sons Pvt. Ltd.',
        address: 'Allana House, Currimbhoy Rd, Mumbai 400001, India',
      },
      shipper: {
        name: 'Agrosuper S.A.',
        address: 'Av. Apoquindo 4501, Las Condes, Santiago, Chile',
      },
      cargo: [
        {
          product: 'KILOS CARNE BOVINA CONGELADA',
          kgNetUnit: 25.0,
          kgGrossUnit: 26.5,
          qty: 880,
          kgNetTotal: 22_000.0,
          kgGrossTotal: 23_320.0,
          fobPrice: 7.85,
        },
      ],
      totalKgNet: 22_000.0,
      totalKgGross: 23_320.0,
    },
    validationStatus: 'failed',
    validationResults: [
      { id: 'CHK-1', checkName: 'Booking reference match', agentId: 'si_validator', result: 'pass', details: 'Matches Booking HLCUNSA218.' },
      { id: 'CHK-2', checkName: 'Container type match', agentId: 'si_validator', result: 'pass', details: '40HC on both.' },
      { id: 'CHK-3', checkName: 'POL match', agentId: 'si_validator', result: 'pass', details: 'San Antonio on both.' },
      { id: 'CHK-4', checkName: 'POD match', agentId: 'si_validator', result: 'pass', details: 'Nhava Sheva on both.' },
      { id: 'CHK-5', checkName: 'Cut-off match', agentId: 'si_validator', result: 'pass', details: 'Cut-off matches Booking.' },
      { id: 'CHK-6', checkName: 'Vessel/voyage match', agentId: 'si_validator', result: 'fail', details: 'SI declares vessel "Northern Vision". Booking has "Northern Defender" on voyage 0218W. Voyage matches; vessel does not. Carrier will reject.', fieldRef: 'vesselVoyage', expected: 'Northern Defender / 0218W', actual: 'Northern Vision / 0218W' },
      { id: 'CHK-7', checkName: 'Required fields present', agentId: 'si_validator', result: 'pass', details: 'All required fields present.' },
      { id: 'CHK-8', checkName: 'Cargo totals reconcile', agentId: 'si_validator', result: 'pass', details: 'Totals reconcile.' },
      { id: 'CHK-9', checkName: 'Reefer setpoint present', agentId: 'si_validator', result: 'pass', details: 'N/A — dry container.' },
      { id: 'CHK-10', checkName: 'Exporter master data match', agentId: 'master_data_sentinel', result: 'pass', details: 'Shipper "Agrosuper S.A." matches master record.' },
    ],
  },

  // ============================================================
  // SI_RECEIVED — validation pending (no results yet)
  // ============================================================
  {
    id: 'SI-MSCSAI4423',
    bookingId: 'BKG-MSCSAI4423',
    receivedAt: '2026-04-30T08:55:00-04:00',
    sourceFileUrl: '/mock-docs/comfrut-1009562-si.pdf',
    sourceFileName: 'SI_Comfrut_MSCSAI4423.pdf',
    uploadedVia: 'portal',
    parsedFields: {
      embarqueNumber: '1009573',
      portOfLoading: 'San Antonio, Chile',
      portOfDischarge: 'Charleston, USA',
      finalDestination: 'Bentonville, AR, USA',
      vesselVoyage: 'MSC Antonia / EX2614R',
      naviera: 'Mediterranean Shipping Company',
      forwarder: 'Interglobo Chile',
      bookingReference: 'MSCSAI4423',
      salesModality: 'Venta a Firme',
      paymentForm: 'COBRANZA',
      incoterm: 'FOB',
      containerCount: '1 UNIDAD REEFER 40 H.C',
      containerType: '40RF',
      setpointC: -18,
      deposito: 'Saam Extraportuario San Antonio',
      generator: 'POR CUENTA DEL TRANSPORTE',
      transport: 'Transportes Andinos Ltda.',
      truckType: 'Tractocamión 6x4 reefer 40\'',
      freightTerms: 'COLLECT',
      returnPeriod: '270 DIAS',
      plant: { name: 'Comfrut S.A. — Planta Linares', address: 'Camino Longitudinal Sur Km 175, Linares', contact: 'Cristián Cifuentes · +56 73 2 540000' },
      loadingDate: '2026-04-30T09:00:00-04:00',
      portArrivalDate: '2026-04-30T18:00:00-04:00',
      stackingFrom: '2026-04-29T08:00:00-04:00',
      stackingTo: '2026-05-01T14:00:00-04:00',
      cutOff: '2026-05-01T16:00:00-04:00',
      consignee: { name: 'Walmart Inc.', address: '702 SW 8th St, Bentonville, AR 72716, USA' },
      notify: { name: 'Expeditors International — Savannah', address: '1 Diamond Causeway, Savannah, GA 31406, USA' },
      shipper: { name: 'Comfrut S.A.', address: 'Camino Longitudinal Sur Km 175, Linares, Chile' },
      cargo: [
        { product: 'KILOS CEREZAS ORGANICO CONGELADO IQF 10 KG', kgNetUnit: 10.0, kgGrossUnit: 10.55, qty: 2286, kgNetTotal: 22_860.0, kgGrossTotal: 24_117.3, fobPrice: 5.92 },
      ],
      totalKgNet: 22_860.0,
      totalKgGross: 24_117.3,
    },
    validationStatus: 'pending',
    validationResults: [],
  },
  {
    id: 'SI-CMACOL112',
    bookingId: 'BKG-CMACOL112',
    receivedAt: '2026-04-30T09:30:00-04:00',
    sourceFileUrl: '/mock-docs/comfrut-1009562-si.pdf',
    sourceFileName: 'SI_Hortifrut_CMACOL112.pdf',
    uploadedVia: 'portal',
    parsedFields: {
      embarqueNumber: 'HFR-2026-0436-12',
      portOfLoading: 'San Antonio, Chile',
      portOfDischarge: 'Long Beach, USA',
      finalDestination: 'Los Angeles, CA, USA',
      vesselVoyage: 'CMA CGM Otello / 0FY1NS1MA',
      naviera: 'CMA CGM Chile S.A.',
      forwarder: 'Interglobo Chile',
      bookingReference: 'CMACOL112',
      salesModality: 'Venta a Firme',
      paymentForm: 'OPEN_ACCOUNT',
      incoterm: 'CIF',
      containerCount: '1 UNIDAD DRY 40 H.C',
      containerType: '40HC',
      deposito: 'STI San Antonio',
      generator: '—',
      transport: 'Sotraser',
      truckType: 'Tractocamión 6x4 dry 40\'',
      freightTerms: 'PREPAID',
      returnPeriod: '180 DIAS',
      plant: { name: 'Hortifrut — Planta Quillota', address: 'Cerro El Plomo 5630, Las Condes, Santiago', contact: 'Felipe Donoso · +56 2 2840 7000' },
      loadingDate: '2026-05-02T09:00:00-04:00',
      portArrivalDate: '2026-05-02T18:00:00-04:00',
      stackingFrom: '2026-04-30T08:00:00-04:00',
      stackingTo: '2026-05-02T10:00:00-04:00',
      cutOff: '2026-05-02T12:00:00-04:00',
      consignee: { name: 'Hortifrut North America Inc.', address: '11 Hortifrut Way, Oxnard, CA 93030, USA' },
      notify: { name: 'Hortifrut North America Inc.', address: '11 Hortifrut Way, Oxnard, CA 93030, USA' },
      shipper: { name: 'Hortifrut S.A.', address: 'Cerro El Plomo 5630, Las Condes, Santiago, Chile' },
      cargo: [
        { product: 'KILOS ARANDANO FRESCO 1.5 KG', kgNetUnit: 1.5, kgGrossUnit: 1.7, qty: 9_600, kgNetTotal: 14_400.0, kgGrossTotal: 16_320.0, fobPrice: 8.40 },
      ],
      totalKgNet: 14_400.0,
      totalKgGross: 16_320.0,
    },
    validationStatus: 'pending',
    validationResults: [],
  },

  // ============================================================
  // ESI_SENT — validated and transmitted, awaiting Draft BL
  // ============================================================
  {
    id: 'SI-CGMUSAV504',
    bookingId: 'BKG-CGMUSAV504',
    receivedAt: '2026-04-19T11:55:00-04:00',
    sourceFileUrl: '/mock-docs/comfrut-1009562-si.pdf',
    sourceFileName: 'SI_Comfrut_CGMUSAV504.pdf',
    uploadedVia: 'portal',
    parsedFields: {
      embarqueNumber: '1009563',
      portOfLoading: 'San Antonio, Chile',
      portOfDischarge: 'Savannah, USA',
      finalDestination: 'Atlanta, GA, USA',
      vesselVoyage: 'Matthew Schulte / 0LI1YN1MA',
      naviera: 'CMA CGM Chile S.A.',
      forwarder: 'Interglobo Chile',
      bookingReference: 'CGMUSAV504',
      salesModality: 'Venta a Firme',
      paymentForm: 'COBRANZA',
      incoterm: 'FOB',
      containerCount: '1 UNIDAD REEFER 40 H.C',
      containerType: '40RF',
      setpointC: -18,
      deposito: 'Saam Extraportuario San Antonio',
      generator: 'POR CUENTA DEL TRANSPORTE',
      transport: 'Transportes Andinos Ltda.',
      truckType: 'Tractocamión 6x4 reefer 40\'',
      freightTerms: 'COLLECT',
      returnPeriod: '270 DIAS',
      plant: { name: 'Comfrut S.A. — Planta Linares', address: 'Camino Longitudinal Sur Km 175, Linares', contact: 'Cristián Cifuentes · +56 73 2 540000' },
      loadingDate: '2026-04-20T09:00:00-04:00',
      portArrivalDate: '2026-04-20T18:00:00-04:00',
      stackingFrom: '2026-04-19T08:00:00-04:00',
      stackingTo: '2026-04-21T12:00:00-04:00',
      cutOff: '2026-04-21T14:00:00-04:00',
      consignee: { name: 'Walmart Inc.', address: '702 SW 8th St, Bentonville, AR 72716, USA' },
      notify: { name: 'Expeditors International — Savannah', address: '1 Diamond Causeway, Savannah, GA 31406, USA' },
      shipper: { name: 'Comfrut S.A.', address: 'Camino Longitudinal Sur Km 175, Linares, Chile' },
      cargo: [
        { product: 'KILOS CEREZAS ORGANICO CONGELADO IQF 10 KG', kgNetUnit: 10.0, kgGrossUnit: 10.55, qty: 2286, kgNetTotal: 22_860.0, kgGrossTotal: 24_117.3, fobPrice: 5.92 },
      ],
      totalKgNet: 22_860.0,
      totalKgGross: 24_117.3,
    },
    validationStatus: 'green',
    validationResults: heroValidationChecks,
    esiGeneratedAt: '2026-04-19T12:18:00-04:00',
    esiTransmittedAt: '2026-04-19T12:21:00-04:00',
    esiTransmissionStatus: 'sent',
  },

  // ============================================================
  // DRAFT_BL_RECEIVED — SIs that produced Draft BLs with discrepancies
  // ============================================================
  {
    id: 'SI-MSCSAI4408',
    bookingId: 'BKG-MSCSAI4408',
    receivedAt: '2026-04-22T10:30:00-04:00',
    sourceFileUrl: '/mock-docs/comfrut-1009562-si.pdf',
    sourceFileName: 'SI_Comfrut_MSCSAI4408.pdf',
    uploadedVia: 'portal',
    parsedFields: {
      embarqueNumber: '1009558',
      portOfLoading: 'San Antonio, Chile',
      portOfDischarge: 'Charleston, USA',
      finalDestination: 'Bentonville, AR, USA',
      vesselVoyage: 'MSC Lorena / EX2611R',
      naviera: 'Mediterranean Shipping Company',
      forwarder: 'Interglobo Chile',
      bookingReference: 'MSCSAI4408',
      blNumber: 'MSCUSAI3052105',
      salesModality: 'Venta a Firme',
      paymentForm: 'COBRANZA',
      incoterm: 'FOB',
      containerCount: '1 UNIDAD REEFER 40 H.C',
      containerType: '40RF',
      setpointC: -18,
      deposito: 'Saam Extraportuario San Antonio',
      generator: 'POR CUENTA DEL TRANSPORTE',
      transport: 'Transportes Andinos Ltda.',
      truckType: 'Tractocamión 6x4 reefer 40\'',
      freightTerms: 'COLLECT',
      returnPeriod: '270 DIAS',
      plant: { name: 'Comfrut S.A. — Planta Linares', address: 'Camino Longitudinal Sur Km 175, Linares', contact: 'Cristián Cifuentes · +56 73 2 540000' },
      loadingDate: '2026-04-23T09:00:00-04:00',
      portArrivalDate: '2026-04-23T18:00:00-04:00',
      stackingFrom: '2026-04-21T08:00:00-04:00',
      stackingTo: '2026-04-23T14:00:00-04:00',
      cutOff: '2026-04-23T16:00:00-04:00',
      consignee: { name: 'Walmart Inc.', address: '702 SW 8th St, Bentonville, AR 72716, USA' },
      notify: { name: 'Expeditors International — Savannah', address: '1 Diamond Causeway, Savannah, GA 31406, USA' },
      shipper: { name: 'Comfrut S.A.', address: 'Camino Longitudinal Sur Km 175, Linares, Chile' },
      cargo: [
        { product: 'KILOS CEREZAS ORGANICO CONGELADO IQF 5x2 KG', kgNetUnit: 10.0, kgGrossUnit: 10.6, qty: 2286, kgNetTotal: 22_860.0, kgGrossTotal: 24_232.0, fobPrice: 5.85 },
      ],
      totalKgNet: 22_860.0,
      totalKgGross: 24_232.0,
    },
    validationStatus: 'green',
    validationResults: heroValidationChecks,
    esiGeneratedAt: '2026-04-22T11:00:00-04:00',
    esiTransmittedAt: '2026-04-22T11:04:00-04:00',
    esiTransmissionStatus: 'acknowledged',
  },
  {
    id: 'SI-CGMURTM910',
    bookingId: 'BKG-CGMURTM910',
    receivedAt: '2026-04-23T10:00:00-04:00',
    sourceFileUrl: '/mock-docs/comfrut-1009562-si.pdf',
    sourceFileName: 'SI_Copefrut_CGMURTM910.pdf',
    uploadedVia: 'portal',
    parsedFields: {
      embarqueNumber: 'CPF-2026-1232',
      portOfLoading: 'San Antonio, Chile',
      portOfDischarge: 'Rotterdam, Netherlands',
      finalDestination: 'Rotterdam, Netherlands',
      vesselVoyage: 'CMA CGM Otello / 0FY1NS1MA',
      naviera: 'CMA CGM Chile S.A.',
      forwarder: 'Interglobo Chile',
      bookingReference: 'CGMURTM910',
      blNumber: 'CGMURTM3041201',
      salesModality: 'Venta a Firme',
      paymentForm: 'CAD',
      incoterm: 'CIF',
      containerCount: '1 UNIDAD DRY 40 H.C',
      containerType: '40HC',
      deposito: 'STI San Antonio',
      generator: '—',
      transport: 'Sotraser',
      truckType: 'Tractocamión 6x4 dry 40\'',
      freightTerms: 'PREPAID',
      returnPeriod: '180 DIAS',
      plant: { name: 'Copefrut S.A. — Planta Curicó', address: 'Camino Las Mariposas s/n, Curicó', contact: 'Andrés Lavín · +56 75 2 322500' },
      loadingDate: '2026-04-24T09:00:00-04:00',
      portArrivalDate: '2026-04-24T18:00:00-04:00',
      stackingFrom: '2026-04-22T08:00:00-04:00',
      stackingTo: '2026-04-24T10:00:00-04:00',
      cutOff: '2026-04-24T12:00:00-04:00',
      consignee: { name: 'AH Vroegop B.V.', address: 'Waalhaven Z.z. 16, 3088 HH Rotterdam, NL' },
      notify: { name: 'AH Vroegop B.V.', address: 'Waalhaven Z.z. 16, 3088 HH Rotterdam, NL' },
      shipper: { name: 'Copefrut S.A.', address: 'Camino Las Mariposas s/n, Curicó, Chile' },
      cargo: [
        { product: 'KILOS MANZANA GALA EXPORT 18 KG', kgNetUnit: 18.0, kgGrossUnit: 19.0, qty: 1080, kgNetTotal: 19_440.0, kgGrossTotal: 20_520.0, fobPrice: 1.42 },
      ],
      totalKgNet: 19_440.0,
      totalKgGross: 20_520.0,
    },
    validationStatus: 'green',
    validationResults: [
      { id: 'CHK-1', checkName: 'Booking reference match', agentId: 'si_validator', result: 'pass', details: 'Matches Booking CGMURTM910.' },
      { id: 'CHK-2', checkName: 'Container type match', agentId: 'si_validator', result: 'pass', details: '40HC on both.' },
      { id: 'CHK-3', checkName: 'POL match', agentId: 'si_validator', result: 'pass', details: 'San Antonio on both.' },
      { id: 'CHK-4', checkName: 'POD match', agentId: 'si_validator', result: 'pass', details: 'Rotterdam on both.' },
      { id: 'CHK-5', checkName: 'Cut-off match', agentId: 'si_validator', result: 'pass', details: 'Cut-off matches Booking.' },
      { id: 'CHK-6', checkName: 'Vessel/voyage match', agentId: 'si_validator', result: 'pass', details: 'CMA CGM Otello / 0FY1NS1MA on both.' },
      { id: 'CHK-7', checkName: 'Required fields present', agentId: 'si_validator', result: 'pass', details: 'All required fields present.' },
      { id: 'CHK-8', checkName: 'Cargo totals reconcile', agentId: 'si_validator', result: 'pass', details: 'Totals reconcile.' },
      { id: 'CHK-9', checkName: 'Reefer setpoint present', agentId: 'si_validator', result: 'pass', details: 'N/A — dry container.' },
      { id: 'CHK-10', checkName: 'Exporter master data match', agentId: 'master_data_sentinel', result: 'pass', details: 'Shipper "Copefrut S.A." matches master record.' },
    ],
    esiGeneratedAt: '2026-04-23T10:30:00-04:00',
    esiTransmittedAt: '2026-04-23T10:33:00-04:00',
    esiTransmissionStatus: 'acknowledged',
  },
];

export function getSIById(id: string): ShippingInstruction | undefined {
  return shippingInstructions.find((s) => s.id === id);
}

export function getSIByBookingId(bookingId: string): ShippingInstruction | undefined {
  return shippingInstructions.find((s) => s.bookingId === bookingId);
}
